MtTlmp1F_MapScripts::
	.byte 0

MtTlmp1F_EventScript_DebugWarpCamper::
	msgbox MtTlmp1F_Text_DebugWarpCamper, MSGBOX_AUTOCLOSE
	end

MtTlmp1F_Text_DebugWarpCamper:
	.string "Hey, buddy!\p"
	.string "This lader down here?\n"
	.string "This is for debugging purposes\n"
	.string "only!\p"
	.string "This isn't the real exit to Mt.\n"
	.string "Tlmp!\p"
	.string "Please remove this from the final\n"
	.string "game!$"