gText_Birch_Welcome::
	.string "Hello.\p"
	.string "Welcome to the world of Pokémon.\p"
	.string "If you're playing this game, you have\n"
	.string "probably played Pokémon before.\p"
	.string "You're probably thinking, “What the hell\n"
	.string "is this game about, and why is this\l"
	.string "different from the other games?”\p"
	.string "I don't fucking know!\p"
	.string "Anyway.\n"
	.string "My name is Professor Twig.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “Pokémon.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is inhabited by\n"
	.string "creatures known as Pokémon.\p"
	.string "Some people keep them as pets,\n"
	.string "but most people battle with them.\p"
	.string "I imagine you'll be battling as well.\p"
	.string "As for me...\p"
	.string "I place bets on them and make a shit\n"
	.string "ton of money in the casinos!\p"
	.string "I know everything about Pokémon!\p"
	.string "Take that, corporate motherfuckers!\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy? Or are you a girl? In\n"
	.string "this day and age, who can tell anymore?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}?$"

gText_Birch_YourePlayer::
	.string "Excellent.\p"
	.string "So your name is {PLAYER}!"
	.string "$"

gText_Birch_ThisIsMyDaughter::
	.string "This is my daughter.\p"
	.string "I named her Brittany when\n"
	.string "my daughter was born.\p"
	.string "Now I'm giving you an opportunity\n"
	.string "to give her a different name,\l"
	.string "if you wish.\p" 
	.string "$"

gOtherText_NewName::
	.string "New Name$"
	
gText_Birch_SoItsRival::
	.string "So it's {RIVAL}?$"

gText_Birch_YourRival::
	.string "Splendid.\p"
	.string "So her name is {RIVAL}!\p"
	.string "Don't want to forget that, now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, {PLAYER}.\p"
	.string "Please see me at my Pokémon Lab\n"
	.string "as soon as you possibly can.\p"
	.string "Don't be late!$"
