ElwoodCityGym_MapScripts::
	.byte 0

ElwoodCityGym_EventScriptRocky::
	end

ElwoodCityGym_Gym_Text_RockyIntro:
	.string "Hi there! I'm Rocky!\n"
	.string "I'm the gym leader here!\p"
	.string "Your Pokémon will find this battle\n"
	.string "very hard! Tough as granite!\p"
	.string "You know how I’m going to win?\n"
	.string "My rock-hard determination!\p"
	.string "Hahaha!\p"
	.string "My Pokémon are BOULDER than yours!\p"
	.string "So brace yourself… you're about to face\n"
	.string "the hardest fight of your life…\l"
	.string "and I mean that literally!\p"
	.string "Let’s ROCK!!!"

ElwoodCityGym_Gym_Text_RockyDefeat:
	.string "Waah! Why did I pick the Rock type?\p"
	.string "I took you for granite…\n"
	.string "and I lost!\p"
	.string "I will give you the gym badge now,\n"
	.string "'cause I lost, you know…$"

ElwoodCityGym_Gym_Text_RockyPostBattle:
	.string "I'm just the first of what you will\n"
	.string "face of the Gym League.\p"
	.string "All the other Gym Leaders\n"
	.string "are stronger than me!$"